
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.konai.companymanagement;

import java.util.Date;
import java.util.logging.Logger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.kona.kms.KmsException;
import com.kona.kms.web.ss.company.bo.CompanyBO;
import com.kona.kms.web.ss.company.model.CompanyModel;
import com.konai.kmsexchangemessage.CompanyInfo;
import com.konai.kmsexchangemessage.CompanyRequestType;
import com.konai.kmsexchangemessage.ResponseType;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-16T13:24:41.830+09:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "CompanyManagementService",
                      portName = "CompanyManagementEndPoint",
                      targetNamespace = "http://www.konai.com/CompanyManagement",
                      wsdlLocation = "/WEB-INF/wsdl/CompanyManagement.wsdl",
                      endpointInterface = "com.konai.companymanagement.CompanyManagementPort")
@Service                   
public class CompanyManagementPortImpl implements CompanyManagementPort {

	private static final Logger logger = Logger.getLogger(CompanyManagementPortImpl.class.getName());

	@Autowired
	private CompanyBO companyBO;
	
    /* (non-Javadoc)
     * @see com.konai.companymanagement.CompanyManagementPort#sendCompanyInfo(com.konai.kmsexchangemessage.CompanyRequestType  companyInfoRequest )*
     */
    public com.konai.kmsexchangemessage.ResponseType sendCompanyInfo(CompanyRequestType req) { 
    	logger.info("Executing operation sendCompanyInfo: " + req);
		
		try {            
			CompanyInfo company = req.getCompanyInfo();
			
			CompanyModel model = new CompanyModel();
			model.setCompanyId(company.getCompanyID());
			model.setCompanyName(company.getCompanyName());
			model.setCompanyTypeCode(company.getCompanyTypeCd());
			model.setCountryCode(company.getCountryCd());
			model.setFax(company.getFax());
			model.setEmail(company.getEmail());
			model.setHomepageUrl(company.getHomepageURL());
			model.setAddress(company.getAddress());
			model.setBizLicenseNo(company.getBusinessLicenseNo());
			model.setOfficeTelNum(company.getOfficeTelephoneNo());
			model.setCompanyStatusCode("Active");
			
			Date now = new Date();
			model.setRegistrationDate(now);
			model.setRegistrationUserId("TSM");
			model.setUpdateDate(now);
			model.setUpdateUserId("TSM");
			
			companyBO.insertCompany(model);
			
			return ResponseType.SUCCESS;
		
		} catch(KmsException e){
		
			logger.info(e.getMessage());
			
			return ResponseType.ALREDY_REG;
		
		}catch (Exception e) {
			logger.info(e.getMessage());
			return ResponseType.FAIL;
		}
    }

}
