package com.konai.companymanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-16T13:24:41.954+09:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "CompanyManagementService", 
                  wsdlLocation = "/WEB-INF/wsdl/CompanyManagement.wsdl",
                  targetNamespace = "http://www.konai.com/CompanyManagement") 
public class CompanyManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.konai.com/CompanyManagement", "CompanyManagementService");
    public final static QName CompanyManagementEndPoint = new QName("http://www.konai.com/CompanyManagement", "CompanyManagementEndPoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/�뺥샇/WSDL/wsdl/CompanyManagement.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CompanyManagementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/�뺥샇/WSDL/wsdl/CompanyManagement.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CompanyManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CompanyManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompanyManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CompanyManagementService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CompanyManagementService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CompanyManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CompanyManagementPort
     */
    @WebEndpoint(name = "CompanyManagementEndPoint")
    public CompanyManagementPort getCompanyManagementEndPoint() {
        return super.getPort(CompanyManagementEndPoint, CompanyManagementPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompanyManagementPort
     */
    @WebEndpoint(name = "CompanyManagementEndPoint")
    public CompanyManagementPort getCompanyManagementEndPoint(WebServiceFeature... features) {
        return super.getPort(CompanyManagementEndPoint, CompanyManagementPort.class, features);
    }

}
