package com.konai.companymanagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-16T13:24:41.945+09:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://www.konai.com/CompanyManagement", name = "CompanyManagementPort")
@XmlSeeAlso({org.globalplatform.namespaces.systems_profiles._1_1.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class, com.konai.kmsexchangemessage.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CompanyManagementPort {

    @WebResult(name = "CompanyInfoResponse", targetNamespace = "http://www.konai.com/KmsExchangeMessage", partName = "CompanyInfoResponse")
    @Action(input = "http://www.konai.com/CompanyManagement/SendCompanyInfoRequest", output = "http://www.konai.com/CompanyManagement/SendCompanyInfoResponse")
    @WebMethod(operationName = "SendCompanyInfo")
    public com.konai.kmsexchangemessage.ResponseType sendCompanyInfo(
        @WebParam(partName = "CompanyInfoRequest", name = "CompanyInfoRequest", targetNamespace = "http://www.konai.com/KmsExchangeMessage")
        com.konai.kmsexchangemessage.CompanyRequestType companyInfoRequest
    );
}
