
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.konai.keymanagement;

import java.util.logging.Logger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.BindingType;

import org.springframework.stereotype.Service;

import com.konai.kmsexchangemessage.ResponseType;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-16T13:25:05.002+09:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "KeyManagementService",
                      portName = "KeyManagementEndPoint",
                      targetNamespace = "http://www.konai.com/KeyManagement",
                      wsdlLocation = "/WEB-INF/wsdl/KeyManagement.wsdl",
                      endpointInterface = "com.konai.keymanagement.KeyManagementPort")
@Service   
@BindingType(javax.xml.ws.soap.SOAPBinding.SOAP12HTTP_BINDING)
public class KeyManagementPortImpl implements KeyManagementPort {

    private static final Logger LOG = Logger.getLogger(KeyManagementPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.konai.keymanagement.KeyManagementPort#sendKeyInfo(com.konai.kmsexchangemessage.KeyInfoRequestType  keyInfoRequest )*
     */
    public com.konai.kmsexchangemessage.ResponseType sendKeyInfo(com.konai.kmsexchangemessage.KeyInfoRequestType keyInfoRequest) { 
    	LOG.info("Executing operation sendKeyInfo");
		System.out.println(keyInfoRequest);
		try {
			ResponseType _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
    }

    /* (non-Javadoc)
     * @see com.konai.keymanagement.KeyManagementPort#sendRequestedBINCert(com.konai.kmsexchangemessage.RequestedBINCertification  requestedBINCertification )*
     */
    public com.konai.kmsexchangemessage.ResponseType sendRequestedBINCert(com.konai.kmsexchangemessage.RequestedBINCertification requestedBINCertification) { 
        LOG.info("Executing operation sendRequestedBINCert");
        System.out.println(requestedBINCertification);
        try {
            com.konai.kmsexchangemessage.ResponseType _return = ResponseType.SUCCESS;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.konai.keymanagement.KeyManagementPort#sendRegisteredBINCert(com.konai.kmsexchangemessage.RegisteredBINCertification  registeredBINCertification )*
     */
    public com.konai.kmsexchangemessage.ResponseType sendRegisteredBINCert(com.konai.kmsexchangemessage.RegisteredBINCertification registeredBINCertification) { 
        LOG.info("Executing operation sendRegisteredBINCert");
        System.out.println(registeredBINCertification);
        try {
            com.konai.kmsexchangemessage.ResponseType _return = ResponseType.SUCCESS;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
