package com.konai.keymanagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.ws.rs.Produces;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.BindingType;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-16T13:25:05.063+09:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://www.konai.com/KeyManagement", name = "KeyManagementPort")
@XmlSeeAlso({org.globalplatform.namespaces.systems_profiles._1_1.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class, com.konai.kmsexchangemessage.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface KeyManagementPort {

    @WebResult(name = "KeyInfoResponse", targetNamespace = "http://www.konai.com/KmsExchangeMessage", partName = "KeyInfoResponse")
    @Action(input = "http://www.konai.com/KeyManagement/SendKeyInfoRequest", output = "http://www.konai.com/KeyManagement/SendKeyInfoResponse")
    @WebMethod(operationName = "SendKeyInfo")
    public com.konai.kmsexchangemessage.ResponseType sendKeyInfo(
        @WebParam(partName = "KeyInfoRequest", name = "KeyInfoRequest", targetNamespace = "http://www.konai.com/KmsExchangeMessage")
        com.konai.kmsexchangemessage.KeyInfoRequestType keyInfoRequest
    );

    @WebResult(name = "RequestedBINCertificationResponse", targetNamespace = "http://www.konai.com/KmsExchangeMessage", partName = "RequestedBINCertificationResponse")
    @Action(input = "http://www.konai.com/KeyManagement/SendRequestedBINCertification", output = "http://www.konai.com/KeyManagement/SendRequestedBINCertificationResponse")
    @WebMethod(operationName = "SendRequestedBINCert")
    public com.konai.kmsexchangemessage.ResponseType sendRequestedBINCert(
        @WebParam(partName = "RequestedBINCertification", name = "RequestedBINCertification", targetNamespace = "http://www.konai.com/KmsExchangeMessage")
        com.konai.kmsexchangemessage.RequestedBINCertification requestedBINCertification
    );

    @WebResult(name = "RegisteredBINCertificationResponse", targetNamespace = "http://www.konai.com/KmsExchangeMessage", partName = "RegisteredBINCertificationResponse")
    @Action(input = "http://www.konai.com/KeyManagement/SendRegisteredBINCertification", output = "http://www.konai.com/KeyManagement/SendRegisteredBINCertificationResponse")
    @WebMethod(operationName = "SendRegisteredBINCert")
    public com.konai.kmsexchangemessage.ResponseType sendRegisteredBINCert(
        @WebParam(partName = "RegisteredBINCertification", name = "RegisteredBINCertification", targetNamespace = "http://www.konai.com/KmsExchangeMessage")
        com.konai.kmsexchangemessage.RegisteredBINCertification registeredBINCertification
    );
}
