package com.konai.keymanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-16T13:25:05.072+09:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "KeyManagementService", 
                  wsdlLocation = "/WEB-INF/wsdl/KeyManagement.wsdl",
                  targetNamespace = "http://www.konai.com/KeyManagement") 
public class KeyManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.konai.com/KeyManagement", "KeyManagementService");
    public final static QName KeyManagementEndPoint = new QName("http://www.konai.com/KeyManagement", "KeyManagementEndPoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/�뺥샇/WSDL/wsdl/KeyManagement.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KeyManagementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/�뺥샇/WSDL/wsdl/KeyManagement.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KeyManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KeyManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KeyManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KeyManagementService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KeyManagementService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KeyManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns KeyManagementPort
     */
    @WebEndpoint(name = "KeyManagementEndPoint")
    public KeyManagementPort getKeyManagementEndPoint() {
        return super.getPort(KeyManagementEndPoint, KeyManagementPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KeyManagementPort
     */
    @WebEndpoint(name = "KeyManagementEndPoint")
    public KeyManagementPort getKeyManagementEndPoint(WebServiceFeature... features) {
        return super.getPort(KeyManagementEndPoint, KeyManagementPort.class, features);
    }

}
